name: flutter_client
description: An example Flutter Fireshift client.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.0.0

  infinite_scroll_pagination: ^3.0.1

  darq: ^1.1.1
  dartz: ^0.9.2

  get_it: ^7.1.3

  http: ^0.13.3

  google_fonts: ^2.1.0

  proviso: ^1.0.1

  intl: ^0.17.0

  rxdart: ^0.27.0

  equatable: ^2.0.0

  logger: ^1.0.0

  cupertino_icons: ^1.0.3

flutter:
  uses-material-design: true